### ISSUE TITLE
Increase the restriction options in RLV (RESTRICT menu)

### ISSUE THREAD

**Issue by Aulen-Helendale** [AVsitter/AVsitter#110]
I was trying to add RLV restriction options to existing ones   https://prntscr.com/luec3w

After giving many laps, and look for information and look at:
* The script [AV] root-RLV and the [AV] root-RLV-extra
* AVsitter2 Support Q & A →→ 678 →   https://goo.gl/AmDU52

I realized that there was NO way to increase the possibilities of the RLV restrictions (as it works now) , which must be configured somewhere or in some way that we do not have access to (as, on the other hand, Code comments in the Q & A entry that I just put… )

Therefore, the question is ... if it is possible that ... who handles the options of the RLV, increase and add things

Right now there are these restrictions (if I'm not wrong)
• "Chat", "sendchat", "sending chat"
• "IM", "sendim", "sending IM"
• "Touch", "touchall", "touching"
• "Names", "shownames", "seeing names"
• "Rez / Edit", "edit, rez", "editing and rezzing objects"
• "Inventory", "showinv", "accessing their inventory"
• "Map", "showworldmap, showminimap", "seeing their map"
• "Location", "showloc", "seeing their location"

And it would be interesting to add some things, so that it can be activated by the RESTRICT menu 
• "Chat-send", "sendchat", "sending chat"
• "Chat-read" (using @ recvchat )
• "IM-send", "sendim", "sending IM"
• "IM-read" (using @ recvim )
• "Touch", "touchall", "touching"
• "Names", "shownames", "seeing names"
• "Blind-beyond10m" (using   @camdrawmin: 0   /  @camdrawmax: 10 /  @camdrawalphamin: 0  /  @camdrawalphamax: 1 )
• "Blind-total" (using   @camdrawmin: 0   /   @camdrawmax: 0    /   @camdrawalphamin: 1   /   @camdrawalphamax: 1 )
• "Rez / Edit", "edit, rez", "editing and rezzing objects"
• "Inventory", "showinv", "accessing their inventory"
• "Map", "showworldmap, showminimap", "seeing their map"
• "Location", "showloc", "seeing their location"

Is this possible? Or ... is there any way that creators can do it? Or is it something that only you can do?

**Comment by Sei-Lisa** [comment]
You can edit your own [AV]root-RLV-extra script to add your own restrictions, but only for those RLV restrictions that are flags.

There is a maximum of 12 restrictions, because there's no paging implemented for that menu. If you try to add more, the script will give an error and the dialog will not be shown. So, you can only add 3 to the existing ones.

I've reformated the `RLV_RESTRICTIONS` list, to make it easier to read. You have the modified script here:

https://github.com/AVsitter/AVsitter/blob/master/AVsitter2/Plugins/AVcontrol/%5BAV%5Droot-RLV-extra.lsl

If you want to add a restriction, you have to add a line to the script that looks like this:

    , "button name", "rlvcommand1,rlvcommand2,...", "text for the restriction"

That is:
1. A comma, then the button name in quotes.
2. A comma, then the RLV commands in quotes, separated by commas (within the quotes) if there's more than one.
3. A comma, then the text for the restriction in quotes. The text is the one that will appear after "\<Name> is [no longer] restricted from ".

An example of 3: If you enter "receiving IMs" in the 3rd field, when the restriction is enabled it will say "\<Name> is restricted from receiving IMs", and when the restriction is disabled again, it will say "\<Name> is no longer restricted from receiving IMs".
