### ISSUE TITLE
Permission Error Sent to Owner of Furniture When Sitter Viewer Settings Revoke Permissions on Stand

### ISSUE THREAD

**Issue by ohhmye** [AVsitter/AVsitter#119]
AVsitter 2.2-03.01
This version of AVsitter is from the redelivery box at the AVsitter inworld location.
Firestorm 6.3.2 (58052) Sep 27 2019 22:41:52 (64bit)

When an avatar's viewer preferences are set to revoke permissions on stand, the owner of the furniture equipped with AVsitter receives the following error message when the avatar stands:
Script trying to trigger animations but PERMISSION_TRIGGER_ANIMATION permission not set

The owner of the furniture will receive the error message every few minutes until the seat with the missing sitter is filled [by any avatar], or the scripts are reset.

Error occurs when there's more than one avatar on the furniture. I haven't been able to re-create it with just one.

To re-create, set viewer preferences to:
Preferences -> Firestorm -> Protection tab -> Revoke Permissions -> Revoke on STAND
Sit your avatar along with another on furniture equipped with AVsitter.
Navigate to a SYNC animation, stand. Repeat until the error is given.

This [video ](https://drive.google.com/file/d/1Btu4XBHZrZ2oglWHH0945e_qTNYVx1K-/view?usp=sharing)shows the error occur. The left screen [Anairah] has viewer set to revoke permissions on stand. The right screen is Clarindabelle's viewer, the owner of the bed.

Frequency of error: 8.5/10

**Comment by Sei-Lisa** [comment]
I tried to reproduce with these steps:

1. Create an object.
2. Add `[AV]adjuster`, `[AV]helper`, a blank `AVpos`, `[AV]sit A` & `[AV]sit B` (twice), and three different animations A1, A2, A3.
3. Edit `AVpos` with the contents specified below.
4. Sit owner.
5. Ensure that Revoke on STAND is selected.
6. Sit a 2nd avatar.
7. Select `synch` button.
8. Unsit 2nd avatar.
9. Check for errors in the next 5 minutes.
10. Repeat steps 6-9 several times.

No errors happened in step 9 at any time.

`AVpos` contents:
```
SITTER 0

POSE p1|A1
SYNC synch|A2

{p1}<0,-0,1.419><0,0,0>

SITTER 1

POSE p2|A1
SYNC synch|A3

{p2}<-0.249,-0.765,1.258><0,0,0>
```

The source of the problem could be a plug-in or a third party script. Some questions:

*  Can you please indicate what other scripts are in the object?
* If `[AV]faces` is in the object, can you UNCHECK the Running checkbox of `[AV]faces` and try again? This sounds similar to what https://github.com/AVsitter/AVsitter/commit/8a10a36515c46d5e740b5e0767b533979f85c94d tried to fix.
* Ideally, if possible, could you send me an object that reproduces the problem?

**Comment by ohhmye** [comment]
I get the error when one avatar has permissions set to revoke NEVER and the other has permissions set to revoke on STAND. I apologize if I wasn't clear on that earlier!

I stripped all of the extraneous scripts from the bed except for what you see here and was able to reproduce the error on the first try:
![PermissionErrorTESTContentsAndAVpos](https://user-images.githubusercontent.com/59848083/72396779-a36c7100-36f2-11ea-80b4-0bf6364c400e.jpg)

You asked that I uncheck the running box for [AV]faces. I removed it instead. Without the [AV]faces script, I did NOT get the error.

I can put something together but I think if you set one avatar to revoke permissions never and the other to revoke on stand, you'll be able to reproduce it yourself. If not, I'll go ahead and do that.

**Comment by Sei-Lisa** [comment]
Thanks, so it seems the error is caused by `[AV]faces` indeed.

I am still unable to reproduce it with a notecard similar to that. I see the possibility of a race condition in case of lag in the sim and dependent on the speed of the user's internet connection, but it doesn't explain why the error is received more than once per stand.

@ohhmye can you please confirm that it keeps giving the error every few minutes, with `[AV]faces` as the only extra script? You shouldn't even need `[AV]adjuster` or `[AV]helper`.

**Comment by ohhmye** [comment]
I removed [AV]adjuster and [AV]helper for this next test which I [recorded](https://drive.google.com/file/d/1cyoqySXOri-XTA09t6J5NgYSF0XZ6QsA/view?usp=sharing).
The error happens on the second stand.
And here is the [noob detector script output](https://avsitter.com/settings.php?q=8023f877-787b-f76d-0172-a41d94b4bcbf).
It has been nearly forty minutes and have not received another error message, though.
You can come check out the bed and its surroundings, if you'd like, to get a sense of the sim conditions, etc. I've sent you a landmark and have added you to the security system.

**Comment by Sei-Lisa** [comment]
OK, so there seems to be more than one problem at play. I have an explanation (and a possible fix) for the one you get immediately on stand-up, but now, my concern is the repeated error that you said you were getting every few minutes, because I presume that this one comes from a different script.

Did you have `[AV]sequence` in the original setup, perchance? Did you have other third party scripts that triggered animations?

I can't log in to SL right now, sorry about that. Also, please note that the AVsitter settings links expire after a while, so the contents are lost now. Anyway, as I said, that particular case is now clear, and I can fix it, so I'm now interested in the repeated error you said you got. No script should be starting or stopping animations that long after the avatar stands up, so there seems to be a bug there.

Technical explanation follows, for those interested - feel free to skip it.

I foresee a possible race condition that goes like this:

1. The avatar stands and revokes permissions.
2. The permissions revocation takes some time (due to network speed) to arrive to the sim.
3. Meanwhile, the `[AV]sit A` script sends the 90065 (stand up) notification to all scripts.
4. `[AV]faces` receives it and, in response, it sends a 90002 (stop overlay animation) message to `[AV]sit A` to stop the animation of the avatar that stood up.
5. `[AV]sit A` receives the message and issues a `llStopAnimation`.

Now, depending on how long step 2 takes in comparison to steps 3-5, the revocation may be received before `[AV]sit A` stops the animations, in which case the error will surface. That explains why it is intermittent too.

One possible fix is to check for permissions again in the 90002 message. That drastically reduces the window of failure to two consecutive function calls (the check and the `llStopAnimation` call), and barring cases of extreme lag or extreme bad luck, it should cure it.

**Comment by ohhmye** [comment]
[AV]sequence was not in the original setup.
There were several other scripts, though. 
I will add them one-by-one to see which causes the error message every few minutes.

**Comment by ohhmye** [comment]
I've been testing but have not been able to duplicate the repeating error. It repeated every time in the past. As soon as I posted this bug report, it stopped doing so. 

Here's a screenshot of the messages I copy/pasted onto a notecard on January 11th showing it repeat every few minutes:
![ErrorSpanNotecard11JAN2020](https://user-images.githubusercontent.com/59848083/72629122-85765a80-3904-11ea-9b54-2219701a86f4.jpg)

I'll keep trying!

@Sei-Lisa, thank you for looking into this issue. Your time and work are appreciated!

**Comment by Sei-Lisa** [comment]
Thanks a lot for your effort with tracking this down. I wish I could help but since I'm unable to reproduce, there is little I can do. Sorry about that.

From the notecard, it appears that the messages are triggered in groups of 5, with 2 to 3 minutes between bursts.

One possibility is that the repeated messages only appear in the original setup with a certain sync animation; maybe one which has something special in it - an ANIM line or something else.

Maybe look for a pose that has an ANIM line with 5 animations or something like that, and try to reproduce with it? It's just a wild guess.

**Comment by ohhmye** [comment]
Your wild guess paid off. The number of error messages triggered DOES correspond to the number of animations in the ANIM line.
I used this line as a test: ANIM Foot|reset|1|b|1|AOeye|1|20N|1|23N|1|22N|3|20N|1|S&L:OFace4|3
and got 8 error messages.
Didn't get it to repeat, though. Will keep trying!

**Comment by ohhmye** [comment]
The first group of errors I get consist of nine messages, which happens to coincide with the number of animations in that ANIM line [ANIM Foot|reset|1|b|1|AOeye|1|20N|1|23N|1|22N|3|20N|1|S&L:OFace4|3].
Will have to get the error to repeat to prove that the number of error messages triggered in the following groups correspond to the number of animations in the ANIM line.
I don't understand why I'm having a difficult time getting the error to repeat when it did so before consistently.

**Comment by ohhmye** [comment]
I sent you the setup shown in this [video](https://drive.google.com/file/d/1AQ5odlriu2iX1kUhys0cdtvol8ATnJM6/view). On the left is the male avatar with viewer set to revoke permission on stand. The right shows the owner of the furniture receiving the error messages.

**Comment by Sei-Lisa** [comment]
Thanks for the video. If that happened just once, it confirms that bad sim lag is at play here.

Here's what I get with your example when I stand up with a link message debugger. The 90065 is the stand-up message. The 90002 are the stop animation ones, the ones that I suspect are triggering the errors, for the aforementioned reasons. Every 2nd and 3rd line is the string and key argument, respectively (both empty for 90201).

```
[10:23:29] Object [TEST]: 154 Seq, Link 1: Num=90065
0
39d93ba3-cc0a-4657-857f-3c6d9f3d210b
[10:23:29] Object [TEST]: 155 Seq, Link 1: Num=90002
SGL
39d93ba3-cc0a-4657-857f-3c6d9f3d210b
[10:23:29] Object [TEST]: 156 Seq, Link 1: Num=90002
SGR
39d93ba3-cc0a-4657-857f-3c6d9f3d210b
[10:23:29] Object [TEST]: 157 Seq, Link 1: Num=90201


[10:23:29] Object [TEST]: 158 Seq, Link 1: Num=90002
SupportCupL
39d93ba3-cc0a-4657-857f-3c6d9f3d210b
[10:23:29] Object [TEST]: 159 Seq, Link 1: Num=90002
SupportCupR
39d93ba3-cc0a-4657-857f-3c6d9f3d210b
```

Most importantly, notice that all messages happen __in the same second__.  In your video, each arrives with a big distance from the previous one. I don't get any other messages after that one, not even after several minutes.

Can you please check the Scripts Run stat in the Ctrl+Shift+1 window? In the sim where I'm testing it's at 96% at worst.

Can you also please try to see if you can reproduce it in a different sim, where Scripts Run is at least at 80%?

**Comment by ohhmye** [comment]
I've started reading up on script lag and found that heavily scripted/populated regions would easily see scripts run at 50% with no major issues. I was at 20% with five avatars in the region!

I've taken steps to reduce the number of scripts on my parcel and am seeing scripts run nearly at 30%, also with five avatars. I have a LOT of furniture rezzed, though, and don't think it likely that I'll get to 50%.

If you can direct me to a sim where scripts run is at least 80% and I can rez, I'll try to reproduce the error.

**Comment by Sei-Lisa** [comment]
**ohhmye** has contacted me inworld to confirm that indeed, she can't reproduce the problem in a sim with a high scripts run %. Thanks!

@ohhmye if I may abuse you one last time, can you please confirm whether this modified `[AV]sitA` version fixes the bug for you? https://raw.githubusercontent.com/Sei-Lisa/AVsitter/sei-fix-perms-error/AVsitter2/%5BAV%5DsitA.lsl

(Please try several times because it can still fail, but I'll be happy if you can confirm that it doesn't fail in say 5 attempts)

I was worried that there was some dangling timer somewhere sending messages, which would be causing lag, and that in that case, the problem was masked by this modification. That would be a worrisome bug. That's why I insisted in addressing the repeated messages before presenting a fix.

**Comment by ohhmye** [comment]
[Tests completed with the modified version of the [AV]sitA script were successful!](https://drive.google.com/file/d/1vAhSHkv7geUeMDeRvQDc2uNiQYTsqffS/view)

Since I've been reducing the number of scripts on my land, I had to rez a lot of extra furniture to get scripts run down to its original 20%.

As for the repeated error messages, no, I could not reproduce them during the tests I did for this bug. They have, though, presented themselves consistently in the past. I just haven't been isolate the culprit.
I share with you the following five chat logs showing the repeated error messages:
[Sitter Spam January 11th, 2020](https://docs.google.com/document/d/1tSA7S1GDrJgvArl9n4BAdiuKrmEd_JbyNfDVJF9OFAQ/edit?usp=sharing)
[Sitter Spam November 15th, 2019](https://docs.google.com/document/d/1eO6ViaTxVaaq6M1QQYuiHKyZd15lynetOvx16PQMAow/edit?usp=sharing)
[Sitter Spam November 10th, 2019](https://docs.google.com/document/d/172KJqHgzapNrhWftLaku9mpz-wuh3OBAi5vtXCxBU5U/edit?usp=sharing)
[Sitter Spam November 3rd, 2019](https://docs.google.com/document/d/101ldHGbk8RQe0oYolw2m6Gm6G_qZBkcfWM0WVG6YiiY/edit?usp=sharing)
[Sitter Spam October 22nd, 2019](https://docs.google.com/document/d/1_bVTShiHtYiVdWMMgzU7_z2WYFM1NeBBPLGmsgP8r7A/edit?usp=sharing)

**Comment by Sei-Lisa** [comment]
Thanks a lot for your testing. I'm actually a bit surprised that the error still shows up on occasion.

The new code is checking whether it has permissions and, if so, it immediately stops the animation. But in these extreme lag conditions, the script is so slow, that the time between the check and the stopping of the animation is relatively long. Specifically, long enough for the permission revocation to have a high enough chance to arrive right in the middle, as to be observable in a few attempts. This kind of problem is called a [Time-of-check to Time-of-use](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use) race condition.

Unfortunately, there's nothing we can do to avoid it; Linden Lab does not provide a way to try to stop an animation and fail silently if there are no permissions, or a way to check and stop atomically, with nothing happening in between. The best that can be done is checking the permissions immediately prior to the start/stop command, in order to reduce the window where a revocation causes problems to a minimum, and that's what the script is doing. If the lag makes the time window large enough for getting failures, that's (second) life.

The only good news is that due to its nature, it can't happen more than once per sitter that the revocation is inserted between the check and the stopping, as you've observed. In all subsequent attempts the revocation will already be effective and therefore detected early enough, thus guaranteeing that it doesn't come more than once (per sitter that stands up).

So I will merge the patch and consider the remaining issue unfixable.

As for the repetitions, my opinion is that several stand-up events could have accumulated during several tests you made (the message queue can hold more than 60 messages). That would explain why you were unable to reproduce it when you tried.

Thanks again!

**Comment by ohhmye** [comment]
I've been dealing with that script error for a long while and it has made me absolutely crazy. I call the patch a win when I see the message once and only during extreme script lag.
You're welcome, and I thank you in return for your time and work!

**Comment by RandalOulton** [comment]
Very glad I found this thread. I was encountering the same inexplicable error message using //2.2-03 . Setting Preferences -> Firestorm -> Protection tab -> Revoke Permissions back to default (Never) solved it.  Glad you documented it; thanks for your work.
