### ISSUE TITLE
Needlessly reloading AVpos notecard

### ISSUE THREAD

**Issue by pfifo** [AVsitter/AVsitter#145]
I am writing a custom script for AVsitter to handle swap functionality for a special circumstance.
When I make modifications to my custom script, sometimes, AVsitter will trigger a reload of the AVpos notecard
(sometimes it will not trigger as well?)
This is unexpected and unneeded as nothing has changed in the setup aside from my own code.
This 'Automated' reloading of AVpos notecard needs to be disabled, or some method of turning it off needs to be added.

**Comment by Sei-Lisa** [comment]
AVsitter autodetects whether the AVpos notecard has changed by monitoring its UUID when the prim inventory changes. This is not likely to be changed.

Things that can cause this autodetection to fail are: that the notecard is not full perms (because when it is not, SL doesn't allow reading the UUID of the notecard - I tried to change that situation but didn't succeed, see https://jira.secondlife.com/browse/BUG-41641) and that the system does not notify of an inventory change (I believe that happens when a script deletes an item in the inventory of the prim, and possibly in more circumstances).

When the notecard UUID is NULL_KEY, AVsitter has no choice but to re-read the notecard whenever the inventory changes, because it no longer has a means to detect whether only the notecard has changed.

**Comment by pfifo** [comment]
So why cant auto detection be disabled? A button in the adjust menu to turn off the feature and another button to trigger a reload manually.
