### ISSUE TITLE
Dump syntax problem

### ISSUE THREAD

**Issue by selticq** [AVsitter/AVsitter#147]
The Dump action return this

POSE|MyPose|MyAnimation 

instead of 

POSE MyPose|MyAnimation

**Comment by Sei-Lisa** [comment]
I can't reproduce this. I followed these steps:

1. Download release 2.2-03.01 from https://github.com/AVsitter/AVsitter/releases/download/2.2-03.01/AVsitter2.2-03.01.zip
2. Extract the folder.
3. Rez 'AVsitter Example#01' from the AVsitter examples box.
4. Replace all scripts inside the example with release 2.2-03.01 downloaded in step 1, just to be sure.
5. Add [AV]helper object and [AV]adjuster script, all with scripts from release 2.2-03.01.
6. Sit on object
7. Click object
8. Click "[Adjust]"
9. Click "[HELPER]"
10. Click "[DUMP]"

The output was:

[07:56:41] ◆
[07:56:41] ◆--✄--COPY BELOW INTO "AVpos" NOTECARD--✄--
[07:56:41] ◆
[07:56:41] ◆"AVSITTER EXAMPLE#01 (BASIC CHAIR)" AVsitter 2.2
[07:56:41] ◆
[07:56:42] ◆POSE Sit1|animation1
[07:56:42] ◆POSE Sit2|animation2
[07:56:42] ◆{Sit1}<-0.024,-0.339,0.968><0,0,-90>
[07:56:43] ◆{Sit2}<-0.024,-0.339,0.899><0,0,-90>
[07:56:43] ◆
[07:56:43] ◆--✄--COPY ABOVE INTO "AVpos" NOTECARD--✄--
[07:56:43] ◆

I can't see anything wrong in that output.

Please specify exact steps to follow in order to reproduce, including which scripts to include and where to get them from.

**Comment by selticq** [comment]
Ok, i've understanded: 

In [AV]adjuster, here is your SEP constant displayed by github : 

string SEP = "�"; // OSS::string SEP = \u007F";

When content of the file is copied from Notepad into the SL Viewer (Firestorm) script editor, the character is replaced by a space :

string SEP = " "; // OSS::string SEP = "\u007F";

So the line 556 in [AV]adjuster :

msg = strReplace(msg, SEP, "|");

replace all spaces characters by a pipe.

When i load directly the script with Firestorm (editor -> import) there is no problem

Thanks for your quick response, an sorry for the disturbance with an external bug.

**Comment by selticq** [comment]
Solved, thanks.
