### ISSUE TITLE
Publishing of settings.php

### ISSUE THREAD

**Issue by RiderDavis** [AVsitter/AVsitter#20]
Incredibly simple request, or suggestion perhaps...

I was just wondering if there was any intentions on or if I could request, adding the settings.php page to the repository or making it available elsewhere, so that individuals with personal servers such as myself may use their own resources instead of avsitter.com when dumping AVpos settings?

Thanks in advance,
~Rider

**Comment by Sei-Lisa** [comment]
Hi RiderDavis,

I do have some plans for a future `settings.php`, but at the moment it's not available. One can just be added to the repository, without any instructions or support whatsoever, leaving it up to the users to set up their database, user, password and server, as giving support for this would be quite complicated. I keep that in mind.

The issue was already raised here, and I gave an inworld script that works as a private web server but only for one notecard at a time:

https://github.com/AVsitter/AVsitter/issues/14#issuecomment-322839456

As the OP of #14 did not reply, would you please check it and see if it's adequate for the length of the notecards that you handle? Do you handle big notecards?

**Comment by RiderDavis** [comment]
First, I should apologize for overlooking the previous issue raised on this matter. My oversight, as I'd taken a gander and hadn't seen anything to this accord. I do apologize for any confusion that may cause. ...I did try the script, works great for shorter notecards for sure but unfortunately I do get the ol' stack heap collision on some of the larger pieces. It also presents a more complicated matter of maintaining the temporary urls should someone need to, as I'm sure you know.

Great for being in a pinch, however!

I could understand and would anticipate there being no official support for personal settings.php use, if there is any way I could entice you to adding it to the repository in spite of the reservations.

Cheers on either accord and have a great weekend!

**Comment by Sei-Lisa** [comment]
Thanks for testing, and don't worry about not finding the other issue, as the inworld server was a bit of an off-topic excursion in that one.

Ok, so an inworld solution seems to be a no-go. Just to clarify, I don't have a `settings.php` myself; I'd have to write one, like I wrote the LSL version. The current `settings.php` was not published.

**Comment by RiderDavis** [comment]
I'm sure we _could_ divide up the data and pass it between other additional scripts for the sake of keeping memory clear on the receiving script itself... But all of that seems wildly inefficient and still doesn't address the long-term problem of the changing URL and so on...

I'd certainly be in favor of a php page _**if**_ you're up for it! Shame we can't get the settings.php from @codeviolet 

Thanks in advance and have a great weekend!

**Comment by codeviolet** [comment]
As stated, the avsitter.com settings.php web service is planned to remain available for use by AVsitter users indefinitely.

However, after noticing several requests about settings.php (#3, #14, #20) it I think it's ok to make the current php script available, and will include it in a PR and hope it's useful to those in the community who want to use it as a starting point for their own instance.

I did not include it in the initial repository, as php and sql are completely separate topics from AVsitter, and there are plenty of tutorials for php/sql on the web that serve as better starting points than my code (that was not originally intended for public consumption).

As the code is run server-side I'd request that if any security vulnerabilities are apparent in my php code, then the community notify me.

Obviously one neat thing to try would be to modify the sit scripts to read the settings in via http, but I never got around to this as my preference was to ensure that the scripts were not reliant on an external server, and would work stand-alone in SL.

I'll add settings.php via PR shortly. I'll also include the "noob-detector" script which also uses settings.php although as I currently have the settings.php database clear every 10 minutes, users who wanted to show the noob-detector results to someone would need to make a copy before the database entry expires.

ps: I think Sei's idea of an http-aware in-world box that one can rez beside the furniture before [DUMP] is a great idea. The changing url could perhaps be overcome by using a listener to receive the settings instead of http but when script memory is an issue for the receiving prim, due to a large notecard, it does become challenging.

**Comment by Sei-Lisa** [comment]
Thanks, @codeviolet. Side note: for the inworld private server, I would have considered further changes to alleviate the URL issues, but the out-of-memory error is a showstopper.

**Comment by Sei-Lisa** [comment]
Closed via #24. `settings.php` has now been contributed to the repository thanks to the generosity of Code Violet. Thanks for your suggestion!

**Comment by RiderDavis** [comment]
Got a hold of the settings.php and was able to have it running in seconds.

Will be fun playing around with it.

**_Thanks~!_** :+1:

**Comment by codeviolet** [comment]
np :) Just be aware there were some updates made to that script overnight which fixed some problems.
