### ISSUE TITLE
Settings Webserver Printout

### ISSUE THREAD

**Issue by Dysfunctionality** [AVsitter/AVsitter#3]
Hello!

This evening while using 2.2 and the AVpos-shifter utility (a favorite!) I am unsure if SL is borking, or if the algorithms have changed, but the text it was spitting out was horrifically out of order and mangled, ie line 29 would be on like 40. It required a lot of manual cleanup, not to mention piping it through to clean up the first 23 characters for my own sanity of readability.

Anyways, and to the point: In the 2.2 versions, the settings printout (this: https://avsitter.com/settings.php?q=xxxx-) no longer exists when saving things out. It is chat only, which as shown above is extremely error prone.

Could you provide the server code for a self hosted option, as well as advise the lsl modifications to allow users to still utilize this without relying on your servers?

As an aside, how long do you anticipate to continue supporting the 2.1-14x versions and this function working on your web server, as I may simply continue using them. I have rolled back to them already.

Thanks
Anke

**Comment by Sei-Lisa** [comment]
Hi Anke, I don't know what problem you may be having but the web site link is working fine for me.

**Comment by codeviolet** [comment]
I have added the web service code back into the AVpos-shifter utility, as we had left it in for the [AV]adjuster anyway.

The web service is _planned_ to remain available indefinitely at this stage, provided it is not abused (the database is cleared regularly so that there should hopefully be little reason for anyone to want to use it for anything else). It should not be used by other (non-avsitter) projects. If it is abused then we may need to place a check in the server code to restrict use to registered avatars, or something similar.

We may make the server-side code available some time in future, but it's outside the scope of current plans. However, you should be able to find plenty of example of web server code (see below).

It is annoying that the order in which scripted chat messages show in SL is unreliable (LL broke it somewhere around 2012 in my experience). Lets hope they fix it again one day :)

---

Just a note: The AVsitter scripts that use that service are not a demonstration of good practice for communicating with web servers. They do not have any error handling in the event the web server request fails for any reason and just hurl the settings at the url hoping that they stick :)

Error checking would have taken up script memory, and the solution seems to work well in any case. But anyone setting up a web server for LSL communication should check the SL wiki http://wiki.secondlife.com/wiki/LlHTTPRequest for proper examples that use ```http_response```. That page also has some simple php for how to handle data sent from SL to a web server.

**Comment by Dysfunctionality** [comment]
Thanks Code! I'm glad to know it'll remain indefinitely. If/when that changes, I'm sure I can figure out how to port it over then.

**Comment by Sei-Lisa** [comment]
Apologies, I saw the Plurk first where the AVpos-shifter utility wasn't mentioned, and didn't notice that the bug report was about that utility.
