### ISSUE TITLE
Unconventional delimeter causing probs in OpenSim

### ISSUE THREAD

**Issue by codeviolet** [AVsitter/AVsitter#41]
The sitA and sitB scripts use a Unicode character ```�``` ([FFFD](https://apps.timwhitlock.info/unicode/inspect?s=%EF%BF%BD)) as a delimiter within the scripts, and this seems to be raising some issues with OpenSim conversion and function:

* This delimiter is only used in internal script memory for a few features such as defining gender for a seat e.g. ```SITTER 0|seat1|F``` and for the "inbuilt sequence" e.g. ```POSE Solo-SEQ|animation1|5|animation2|5```.

* The character is not present in ```.oss``` files generated by the Makefile, being replaced by Unicode [001F](https://apps.timwhitlock.info/unicode/inspect?s=%1F). The scripts compile and appear to work fine with the ```001F``` delimiter but oddly were causing the scripts to refuse to allow 'Hypergrid Export' under Kitely while the script memory contained strings using this delimiter (i.e. an issue for Kitely/OpenSim devs to resolve some day).

* Anyway when original ```�``` (FFFD) delimiter is re-inserted into the sitA & sitB scripts in OpenSim, the features that use the delimiter do not work.

* I have temporarily changed all occurrences of ```�``` (FFFD) to a plain-text delimiter ```@#@``` in the OpenSim package I am preparing. This replacement alleviates the problem, but obviously this needs to be fixed at the source when convenient.

The use of the Unicode delimiter may cause additional problems, so I think should be removed entirely from the code, but I'm not sure what it's best to change it to. It needs to be a sequence that users are not going to use in their menus and pose/seat names, and short as possible for memory conservation. I will defer to @Sei-Lisa's expertise to decide how the replacement of this delimiter is best handled.

**Comment by Sei-Lisa** [comment]
I didn't remove it from the SL code, and chose to instead replace it automatically in Python in order to generate the OpenSim version, because I feared that since that character is exposed to other scripts through link messages, it could cause incompatibilities with user-made plugins to remove it.

I have an idea to solve this problem. I'll see whether it is viable.

I am wondering now whether that's the cause of #39.

**Comment by Sei-Lisa** [comment]
Now that I look again, I don't know where I got the idea that it was exposed in link messages. And now that I read you again, you're saying it isn't. So perhaps in SL it can just be replaced by U+001F and leave it with the run-time assignment for OpenSim.

**Comment by codeviolet** [comment]
It will be exposed in link messages, e.g. ```AVsitter Example#07a```, testing in SL, with the following test script in the prim:

```
default
{
    link_message(integer sender, integer num, string msg, key id){
        llOwnerSay("l:"+(string)num+" m:"+msg+" i:"+(string)id);
    }
}
```

Choosing ```Solo-SEQ``` from the menu shows that it is exposed in the ```90045``` link message, with the chat output:

```
l:90045 m:0|Solo-SEQ|animation1�10�animation2�10�animation3�10|-1|f2e0ed5e-6592-4199-901d-a659c324ca94@|Couples-SEQ|0 i:f2e0ed5e-6592-4199-901d-a659c324ca94
```

So it is there in link messages, but only in cases where the notecard is using certain features that use the delimiter.
 
U+001F appears as a blank character in my script edit window and probably not a good idea to use. 

Perhaps we should define the delimiter as a global variable, like you have, but choose a better delimiter that works in both SL and OpenSim. ```@#@``` works as a replacement, but is that the best delimiter to use?

**Comment by codeviolet** [comment]
I should add, that this delimiter is used only when the pipe ```|``` was already used and thus not available, that's why it's only used for a few features like [“Built-In” animation sequence](https://avsitter.github.io/avsitter2_avpos.html#built-in-animation-sequence) and [Auto-assign by gender](https://avsitter.github.io/avsitter2_avpos.html#auto-assign-by-gender).

**Comment by Sei-Lisa** [comment]
If it's exposed to link messages, perhaps it's best to leave it as is in SL, for compatibility. Third-party plug-ins that are exported from SL to OpenSim will need porting.

I've been making some tests in Kitely and I couldn't reproduce the issue of the character U+001F. I tried this script:

```lsl
string SEP;

default
{
    state_entry()
    {
        SEP = llUnescapeURL("%1F");
    }
    touch_start(integer n)
    {
        llSay(0, llEscapeURL(SEP));
    }
}
```

That script let me export just fine. The ability to export seemed only to depend on the script permissions. I also tried replacing llUnescapeURL("%1F") with the actual U+001F in the source and it didn't cause any problems with exporting.

Maybe the problem is with packaged scripts in nested contents?

**Comment by Sei-Lisa** [comment]
I've closed PR #42 but maybe it's worth revisiting. Have you tried the zip attached there?

I remember getting an extended permissions window with the Export checkbox at some point, but I can't get it to show now. Is there a trick of some kind to make it appear?

**Comment by codeviolet** [comment]
I don't know about an extended permissions window. With my Kitely avatar, I see an 'Export' checkbox when viewing the permissions of an item in my inventory or in the inventory of an object, but not when I edit an in-world object.

I have tried the .zip posted in #42, and the item also won't export with those scripts.

Please try the box labeled "WONT EXPORT" from the AVsitter Sandbox in Kitely. Everything in the box is fullperm yet it does not Export. That's as far as I have narrowed the problem down. 

The easiest test I have been using in Kitely to see whether an item will 'Export' is to try and move the item from inventory to my 'My Suitcase' folder. With the prim I have placed in the sandbox I get the error:

```Can't move item "WONT EXPORT" to this folder because it's not Exportable.``` despite all contents being exportable.

**Comment by Sei-Lisa** [comment]
That's very puzzling. Have you narrowed it down to one of the scripts? Does it happen with either? Does replacing `%1F` with something like `%21` make it exportable? Which one?

I've placed another box near your boxes. It has "Take Copy" enabled. It contains the same scripts from the zip in #42. My OSgrid avatar can take it without problems. May it be an issue with the viewer's Export checkbox?

I guess you mean the permissions in the properties window. I saw that Export checkbox at some point, but I can't see it anymore, which is also puzzling. Not in inventory, not inworld, not in object contents. I'm testing now with a Kitely account (Sei Lisa wasn't taken on Kitely, so I took it) but no dice.

**Comment by codeviolet** [comment]
When I take your object with my Kitely avatar and attempt to move it to the "My Suitcase" folder, I get the message
```
Can't move item "Object that will export (take copy with OSgrid avi works)" to this folder because it's not Exportable.
```
If your Kitely avatar takes it, what happens when they try and move it into the "My Suitcase" folder?


As far as I could determine, it originally had something to do with the ```�``` delimiter, but only when it was called into use by a specific notecard, and not by the script itself containing it. That's why I was having problems exporting only certain examples. Changing this delimiter to a plain-text delimiter ```@#@``` has removed the problem, allowing me to export all examples, but still does not explain the problem :)

My viewer is Firestorm 5.0.7 (52912)

**Comment by Sei-Lisa** [comment]
Thank you for the tip, I could indeed reproduce it that way. Even the simple script posted inline in #42 fails.

Something that still puzzles me that my OSgrid avatar could grab a copy and get it to OSgrid even though it's supposedly not Exportable. It makes me wonder what's the Exportable flag for. That's what confused me thinking it was exportable, my apologies. Anyway, I seem to recall you saying that being exportable is a pre-requisite for Kitely Market, so it's still a showstopper.

I've tried all control characters in the U+0000-U+001F range. The only characters allowed are U+0000 (NUL), U+0009 (HT), U+000A (LF) and U+000D (CR). That selectivity makes me think that the rejection is intentional, though I'm not sure about the reason.

I'm not comfortable at all with using U+0000, as that looks too prone to triggering other bugs. I think I've seen U+000A used in some AVsitter link message, so that one is discarded too. U+0009 and U+000D might perhaps appear by accident in the middle of a notecard while copy pasting, so better not use them.

The possible separators I've been considering are U+007F (DEL), U+0091 (PU1, Private Use 1) and U+2029 (Paragraph Separator). Neither of them makes llParseStringXXXX misbehave; all of them allow export. The less hackish of them would be U+0091, but it's also the most problem-prone, because that code point is a character in CP1252, so one could slip into a notecard if there's an encoding problem while copy pasting.

I'm leaning towards U+007F. It's going to be a hack no matter what, and that one is the shortest. I'll resend #42 with that change.

Side note: My problem with the disappearance of the Export checkbox was caused by me switching the skin to Vintage. Apparently this skin does not support it. Changing the skin back to the default (Firestorm) fixed it.
