### ISSUE TITLE
The Missing-anim-finder script - variable speed animations does not handle correctly

### ISSUE THREAD

**Issue by Flyua** [AVsitter/AVsitter#80]
The Missing-anim-finder script v 2.2-03 produces incorrect messages about the presence of  а "surplus" animations which are correctly described and used as described  [there.](https://avsitter.github.io/avsitter2_avpos.html#variable-speed-animations)

**Comment by codeviolet** [comment]
I have merged PR #83 that should fix this issue

**Comment by Sei-Lisa** [comment]
It would be nice if the OP can confirm whether this script fixes the issue for them: https://github.com/AVsitter/AVsitter/raw/df6de8f5562048f9029321dfa6bcca999f0a593d/AVsitter2/Utilities/Missing-anim-finder.lsl

**Comment by Flyua** [comment]
After last fix Missing-anim-finder script does not work as expected anyway.
If you delete the key "|V" from  the MENU commands in AVpos notecard (that equal to disable this feature for end user), but forget to delete (keep) the animation set with symbol +/- in the inventory (which in this case are not used, and is garbage), the script does not give any messages while doing it.

**Comment by Flyua** [comment]
Hello,
After last fix Missing-anim-finder script does not work as expected anyway.
If you delete the key "|V" from the MENU commands in AVpos notecard (that
equal to disable this feature for end user), but forget to delete (keep)
the animation set with symbol +/- in the inventory (which in this case are
not used, and is garbage), the script does not give any messages while
doing it.

2018-02-13 11:31 GMT+02:00 codeviolet <notifications@github.com>:

**Comment by Sei-Lisa** [comment]
Thanks for testing. Reopening.

**Comment by codeviolet** [comment]
Apologies for my closing of this issue before feedback.

The fix I merged means that the script will not report variable speed anims as "surplus" if their normal speed version is used in the notecard, which I believe satisfies the OP's original issue as it was described. I also believe this is the most serious issue because combined with the option to delete surplus anims, the issue could break working furniture by removing the variable speed anims.

However as the OP correctly points out, my initial patch does not check for the ```|V``` flag before approving variable-speed anims, and it will not notice when variable-speed anims are missing either.

Detecting surplus and missing variable-speed anims on the basis of whether any submenus are flagged with ```|V``` required extensive modification to the script, which I have done. I am not particularly happy with the extra level of script complexity, but it seems to be working for me.

@Flyua, could you please test [this version of the script](https://raw.githubusercontent.com/AVsitter/AVsitter/missing-anim-finder-cv/AVsitter2/Utilities/Missing-anim-finder.lsl) when convenient and tell us if that works for you as expected now, or if there are still issues?

**Comment by Flyua** [comment]
Hello, everything looks fine now. Thank you very much.


2018-02-15 8:05 GMT+02:00 codeviolet <notifications@github.com>:

**Comment by Sei-Lisa** [comment]
Fixed by the latest commit. Thanks for the report.
